language: node_js
node_js:
  - v12.9.1
services:
  - postgresql
postgres:
  adapter: postgresql
  database: test_db
  address: '127.0.0.1'
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
scripts: npm run test
